# Generated by Django 3.2 on 2021-05-19 02:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.code_generator, max_length=8, unique=True),
        ),
    ]
